providers = ["php"]

[variables]
NIXPACKS_NODE = "false"

[phases.setup]
nixPkgs = ["phpPackages.composer"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "chmod -R 775 storage bootstrap/cache"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"